"""Provider-neutral Model Adapter ports and the deterministic tracer adapter."""

from __future__ import annotations

import json
import re
import time
from abc import ABC, abstractmethod
from typing import Any, Mapping, Protocol

from .contracts import AdapterResult


class AdapterError(RuntimeError):
    """Base error that is safe to convert into a provider status."""

    failure_class = "adapter_error"


class AdapterUnavailable(AdapterError):
    failure_class = "unavailable"


class ModelAdapter(Protocol):
    provider: str

    async def generate(
        self,
        prompt: str,
        *,
        model: str,
        deadline: float | None = None,
        **options: Any,
    ) -> AdapterResult:
        """Return provider-neutral raw text and call metadata."""


class BaseModelAdapter(ABC):
    provider = "unknown"

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        *,
        model: str,
        deadline: float | None = None,
        **options: Any,
    ) -> AdapterResult:
        raise NotImplementedError


class DeterministicAdapter:
    """A no-network Adapter used for local development and acceptance fixtures."""

    provider = "deterministic"

    def __init__(self, *, answer_prefix: str = "Deterministic answer") -> None:
        self.answer_prefix = answer_prefix
        self.prompts: list[str] = []

    async def generate(
        self,
        prompt: str,
        *,
        model: str = "deterministic",
        deadline: float | None = None,
        **options: Any,
    ) -> AdapterResult:
        del deadline, options
        started = time.perf_counter()
        self.prompts.append(prompt)
        question_match = re.search(r"^Question:\n(.*?)\n\nConstraints", prompt, re.DOTALL | re.MULTILINE)
        question = question_match.group(1).strip() if question_match else "the submitted question"
        type_match = re.search(r"^Selected question type:\s*(\w+)", prompt, re.MULTILINE)
        claim_type = type_match.group(1) if type_match else "fact"
        if claim_type not in {"fact", "code", "math", "logic", "opinion", "recommendation"}:
            claim_type = "fact"
        payload = {
            "answer": f"{self.answer_prefix}: {question}",
            "reasoning": "Generated by the deterministic acceptance adapter.",
            "claims": [
                {
                    "claim": f"The submitted question is: {question}",
                    "type": claim_type,
                    "confidence": 0.5,
                    "source": None,
                    "assumptions": None,
                }
            ],
            "constraints_check": {},
        }
        return AdapterResult(
            raw_text=json.dumps(payload, ensure_ascii=False),
            provider=self.provider,
            model=model,
            latency_ms=(time.perf_counter() - started) * 1000,
            status="ok",
        )


class UnavailableAdapter:
    """Placeholder for configured providers whose credentials are absent."""

    provider = "unavailable"

    def __init__(self, *, model: str, reason: str = "provider is not configured") -> None:
        self.model = model
        self.reason = reason

    async def generate(
        self,
        prompt: str,
        *,
        model: str | None = None,
        deadline: float | None = None,
        **options: Any,
    ) -> AdapterResult:
        del prompt, model, deadline, options
        raise AdapterUnavailable(self.reason)


class AdapterRegistry:
    """Stable model-name to Adapter mapping with no provider SDK leakage."""

    def __init__(self, adapters: Mapping[str, ModelAdapter] | None = None) -> None:
        self._adapters = dict(adapters or {})

    def register(self, model: str, adapter: ModelAdapter) -> None:
        self._adapters[model] = adapter

    def known_models(self) -> set[str]:
        return set(self._adapters)

    def usable_models(self) -> set[str]:
        return {
            name
            for name, adapter in self._adapters.items()
            if not isinstance(adapter, UnavailableAdapter)
        }

    def get(self, model: str) -> ModelAdapter:
        try:
            return self._adapters[model]
        except KeyError as exc:
            raise AdapterUnavailable(f"model '{model}' is not configured") from exc


def default_adapter_registry(models: list[str]) -> AdapterRegistry:
    registry = AdapterRegistry()
    for model in models:
        if model in {"deterministic", "test", "fake"}:
            registry.register(model, DeterministicAdapter())
        else:
            registry.register(model, UnavailableAdapter(model=model))
    return registry


# Explicit test-facing name keeps fixtures readable without introducing a second
# implementation or a provider-specific import path.
DeterministicTestAdapter = DeterministicAdapter
